
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMA ID LPAREN MENSAJE NUMBER PLUS PUNTO RPAREN SEMICOLON STRING TEXTO TIMESsentencias : sentencias sentencia\n                  | sentenciasentencia : ID ASSIGN expresion SEMICOLONsentencia : MENSAJE PUNTO TEXTO LPAREN STRING RPAREN SEMICOLONexpresion : expresion PLUS expresion\n                 | expresion TIMES expresionexpresion : LPAREN expresion RPARENexpresion : NUMBERexpresion : STRINGexpresion : ID'
    
_lr_action_items = {'ID':([0,1,2,5,6,10,14,15,16,24,],[3,3,-2,-1,8,8,-3,8,8,-4,]),'MENSAJE':([0,1,2,5,14,24,],[4,4,-2,-1,-3,-4,]),'$end':([1,2,5,14,24,],[0,-2,-1,-3,-4,]),'ASSIGN':([3,],[6,]),'PUNTO':([4,],[7,]),'LPAREN':([6,10,13,15,16,],[10,10,18,10,10,]),'NUMBER':([6,10,15,16,],[11,11,11,11,]),'STRING':([6,10,15,16,18,],[12,12,12,12,22,]),'TEXTO':([7,],[13,]),'SEMICOLON':([8,9,11,12,19,20,21,23,],[-10,14,-8,-9,-5,-6,-7,24,]),'PLUS':([8,9,11,12,17,19,20,21,],[-10,15,-8,-9,15,15,15,-7,]),'TIMES':([8,9,11,12,17,19,20,21,],[-10,16,-8,-9,16,16,16,-7,]),'RPAREN':([8,11,12,17,19,20,21,22,],[-10,-8,-9,21,-5,-6,-7,23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sentencias':([0,],[1,]),'sentencia':([0,1,],[2,5,]),'expresion':([6,10,15,16,],[9,17,19,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sentencias","S'",1,None,None,None),
  ('sentencias -> sentencias sentencia','sentencias',2,'p_sentencias','script.py',58),
  ('sentencias -> sentencia','sentencias',1,'p_sentencias','script.py',59),
  ('sentencia -> ID ASSIGN expresion SEMICOLON','sentencia',4,'p_sentencia_asignacion','script.py',62),
  ('sentencia -> MENSAJE PUNTO TEXTO LPAREN STRING RPAREN SEMICOLON','sentencia',7,'p_sentencia_mensaje','script.py',67),
  ('expresion -> expresion PLUS expresion','expresion',3,'p_expresion_binaria','script.py',71),
  ('expresion -> expresion TIMES expresion','expresion',3,'p_expresion_binaria','script.py',72),
  ('expresion -> LPAREN expresion RPAREN','expresion',3,'p_expresion_paren','script.py',79),
  ('expresion -> NUMBER','expresion',1,'p_expresion_num','script.py',83),
  ('expresion -> STRING','expresion',1,'p_expresion_string','script.py',87),
  ('expresion -> ID','expresion',1,'p_expresion_id','script.py',91),
]
